"""
RailETA AI Natural Language Explanation Layer
Problem Statement: SIH26028 (Dynamic Forecast of ETA for Coaching Trains)

Converts structured mathematical ML predictions, operational features, and delay drift
into clear, concise, passenger-friendly natural language explanations using an LLM.

STRICT SAFETY INVARIANT:
The LLM never computes, alters, or overrides numerical ETAs.
All numbers originate strictly from the trained XGBoost / GBDT model.
If the LLM API is unavailable, times out, or lacks an API key, the system gracefully
falls back to the rule-based operational explanation engine with zero disruption.
"""

import os
import time
import logging
from typing import Dict, Any, List, Optional
import httpx

logger = logging.getLogger("raileta.llm_explainer")


class AIExplanationService:
    """
    Optional natural language explanation engine.
    Wraps LLM APIs (Gemini / OpenAI / Custom) with instant fallback.
    """

    def __init__(self):
        self.gemini_api_key = os.getenv("GEMINI_API_KEY", os.getenv("GOOGLE_API_KEY", ""))
        self.openai_api_key = os.getenv("OPENAI_API_KEY", "")
        self.timeout_sec = 3.5

    def generate_explanation(
        self,
        train_number: str,
        train_name: str,
        train_type: str,
        current_station: str,
        next_station: str,
        destination_station: str,
        current_speed_kmh: float,
        current_delay_min: float,
        scheduled_eta_str: str,
        baseline_eta_str: str,
        predicted_eta_str: str,
        delay_drift_min: float,
        confidence_range: List[float],
        operational_factors: List[str],
        section_congestion_level: float = 0.55,
        weather_fog_active: bool = False,
    ) -> Dict[str, Any]:
        """
        Generates a human-readable AI explanation from structured ML outputs.
        """
        # Try calling LLM API if key is present
        if self.gemini_api_key:
            try:
                explanation = self._call_gemini_api(
                    train_number=train_number,
                    train_name=train_name,
                    train_type=train_type,
                    current_station=current_station,
                    next_station=next_station,
                    destination_station=destination_station,
                    current_speed_kmh=current_speed_kmh,
                    current_delay_min=current_delay_min,
                    scheduled_eta_str=scheduled_eta_str,
                    baseline_eta_str=baseline_eta_str,
                    predicted_eta_str=predicted_eta_str,
                    delay_drift_min=delay_drift_min,
                    confidence_range=confidence_range,
                    operational_factors=operational_factors,
                    section_congestion_level=section_congestion_level,
                    weather_fog_active=weather_fog_active,
                )
                if explanation:
                    return explanation
            except Exception as e:
                logger.warning(f"Gemini API explanation failed, falling back to rule engine: {e}")

        # Fallback to deterministic operational explanation generator
        return self._generate_rule_based_explanation(
            train_number=train_number,
            train_name=train_name,
            train_type=train_type,
            current_station=current_station,
            next_station=next_station,
            destination_station=destination_station,
            current_delay_min=current_delay_min,
            delay_drift_min=delay_drift_min,
            confidence_range=confidence_range,
            operational_factors=operational_factors,
            weather_fog_active=weather_fog_active,
            section_congestion_level=section_congestion_level,
        )

    def _call_gemini_api(self, **kwargs) -> Optional[Dict[str, Any]]:
        """Invokes Google Gemini API with strict structured prompt."""
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={self.gemini_api_key}"

        prompt = f"""
You are the RailETA AI Operational Assistant for Indian Railways.
Explain the dynamic ETA forecast for Train {kwargs['train_number']} ({kwargs['train_name']}).

CRITICAL RULE: DO NOT change or calculate any numbers. Use the exact numbers below generated by our ML model.

FACTS:
- Train Type: {kwargs['train_type']}
- Section: {kwargs['current_station']} -> {kwargs['next_station']} (Heading to {kwargs['destination_station']})
- Current Speed: {kwargs['current_speed_kmh']} km/h
- Current Observed Delay: {kwargs['current_delay_min']} minutes
- Timetable Scheduled Arrival: {kwargs['scheduled_eta_str']}
- Naive Schedule+Delay Baseline: {kwargs['baseline_eta_str']}
- ML Model Predicted Arrival: {kwargs['predicted_eta_str']}
- Delay Drift (vs timetable): {kwargs['delay_drift_min']:+0.1f} minutes
- 80% Confidence Interval: [{kwargs['confidence_range'][0]} min, {kwargs['confidence_range'][1]} min]
- Section Congestion: {kwargs['section_congestion_level']}
- Winter Fog Active: {kwargs['weather_fog_active']}
- Key Factors: {', '.join(kwargs['operational_factors'])}

Provide a concise 2-sentence summary explaining WHY the ML ETA differs from the timetable, and 2 short bullet points for passengers.
Format:
SUMMARY: <summary>
POINTS:
- <point 1>
- <point 2>
ADVICE: <passenger advice>
"""

        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {"temperature": 0.2, "maxOutputTokens": 200},
        }

        with httpx.Client(timeout=self.timeout_sec) as client:
            resp = client.post(url, json=payload)
            if resp.status_code == 200:
                data = resp.json()
                text = data["candidates"][0]["content"]["parts"][0]["text"]
                return self._parse_llm_response(text, "GEMINI_LIVE")

        return None

    def _parse_llm_response(self, text: str, engine_tag: str) -> Dict[str, Any]:
        """Parses LLM formatted text into structured dictionary."""
        lines = [line.strip() for line in text.split("\n") if line.strip()]
        summary = ""
        points = []
        advice = "Monitor live train status as section progress updates."

        for line in lines:
            if line.startswith("SUMMARY:"):
                summary = line.replace("SUMMARY:", "").strip()
            elif line.startswith("- "):
                points.append(line.replace("- ", "").strip())
            elif line.startswith("ADVICE:"):
                advice = line.replace("ADVICE:", "").strip()

        if not summary and lines:
            summary = lines[0]

        return {
            "summary": summary or "Dynamic ML forecast calibrated against current track and speed telemetry.",
            "operational_bullet_points": points or [
                "ETA calibrated using real-time headway and track occupancy.",
                "High-priority dispatch cleared along main trunk line."
            ],
            "confidence_assessment": "80% empirical holdout confidence window.",
            "passenger_advice": advice,
            "generated_by": f"LLM_{engine_tag}",
            "is_fallback": False,
        }

    def _generate_rule_based_explanation(self, **kwargs) -> Dict[str, Any]:
        """
        Deterministic, zero-latency rule-based explanation engine (Fallback).
        Translates mathematical feature contributions into fluent English.
        """
        drift = kwargs["delay_drift_min"]
        delay = kwargs["current_delay_min"]
        t_type = kwargs["train_type"]
        fog = kwargs["weather_fog_active"]
        stn = kwargs["next_station"]
        dest = kwargs["destination_station"]

        bullets = []

        # 1. Delay drift direction
        if drift < -1.0:
            summary = f"{kwargs['train_name']} is running efficiently, recovering {abs(drift):.1f} mins of timetable slack before {stn}."
            bullets.append(f"Clear tracks and high locomotive cruising speed allow recovery toward {dest}.")
        elif drift > 1.0:
            summary = f"Expected arrival at {stn} is adjusted by +{drift:.1f} mins due to operational headway constraints."
            bullets.append(f"Section congestion and junction approach queues add minor clearance friction.")
        else:
            summary = f"{kwargs['train_name']} is maintaining steady timetable progression toward {stn}."
            bullets.append("Nominal section running within standard timetable margins.")

        # 2. Priority / Weather nuances
        if fog:
            bullets.append("Winter fog visibility caution in effect (speed restricted for safety).")
        elif t_type in ["VB", "RAJ"]:
            bullets.append(f"Priority {t_type} status gives green signal preference over freight & passenger rakes.")

        if delay > 25.0:
            advice = f"Train is running +{delay:.0f}m behind schedule. Arrive at platform 10-15 mins prior to dynamic ETA."
        else:
            advice = "Train is running on or near schedule. Proceed normally to boarding platform."

        return {
            "summary": summary,
            "operational_bullet_points": bullets,
            "confidence_assessment": f"80% confidence window: [{kwargs['confidence_range'][0]:.1f}m, {kwargs['confidence_range'][1]:.1f}m]",
            "passenger_advice": advice,
            "generated_by": "RULE_BASED_ENGINE",
            "is_fallback": True,
        }


# Global singleton instance
ai_explainer_service = AIExplanationService()
