#!/usr/bin/env python3
"""
RailETA AI Explanation Layer Test Suite
Problem Statement: SIH26028 (Dynamic Forecast of ETA for Coaching Trains)

Verifies:
1. AI explanation receives structured ML facts without LLM calculating numbers.
2. Direct service invocation of AIExplanationService.
3. Resilient fallback when API is offline.
4. FastAPI endpoint POST /api/v1/trains/{id}/ai-explain response contract.
"""

import os
import sys
from fastapi.testclient import TestClient

# Add backend directory to sys.path
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(script_dir)
sys.path.insert(0, os.path.join(project_root, "backend"))

from app.main import app
from app.services.llm_explainer import ai_explainer_service


def test_ai_explainer():
    print("=" * 82)
    print(" RailETA AI Explanation Layer Verification Test (SIH26028) ")
    print("=" * 82)

    # 1. Direct Service Unit Test (Under Delay Recovery Scenario)
    print("\n[1] Testing AIExplanationService direct invocation (Delay Recovery)...")
    res_recovery = ai_explainer_service.generate_explanation(
        train_number="12302",
        train_name="Howrah Rajdhani Express",
        train_type="RAJ",
        current_station="CNB",
        next_station="PRYJ",
        destination_station="HWH",
        current_speed_kmh=118.0,
        current_delay_min=14.0,
        scheduled_eta_str="2026-08-29 23:30",
        baseline_eta_str="2026-08-29 23:44",
        predicted_eta_str="2026-08-29 23:39",
        delay_drift_min=-5.0,  # Recovered 5 minutes
        confidence_range=[-3.6, +3.6],
        operational_factors=[
            "Priority RAJ dispatch cleared green signal path",
            "High cruising speed along triple-line Kanpur-Prayagraj section"
        ],
        section_congestion_level=0.45,
        weather_fog_active=False,
    )

    print(f"  -> Generated By: {res_recovery['generated_by']} (Fallback: {res_recovery['is_fallback']})")
    print(f"  -> Summary     : {res_recovery['summary']}")
    print(f"  -> Bullet Points:")
    for bp in res_recovery["operational_bullet_points"]:
        print(f"     * {bp}")
    print(f"  -> Advice      : {res_recovery['passenger_advice']}")

    # 2. Direct Service Unit Test (Under Fog/Congestion Disruption Scenario)
    print("\n[2] Testing AIExplanationService under Fog/Disruption Scenario...")
    res_fog = ai_explainer_service.generate_explanation(
        train_number="12004",
        train_name="Lucknow Shatabdi Express",
        train_type="SHT",
        current_station="NDLS",
        next_station="GZB",
        destination_station="LKO",
        current_speed_kmh=45.0,
        current_delay_min=35.0,
        scheduled_eta_str="2026-08-29 11:40",
        baseline_eta_str="2026-08-29 12:15",
        predicted_eta_str="2026-08-29 12:28",
        delay_drift_min=+13.0,  # Slowed down
        confidence_range=[-4.2, +4.2],
        operational_factors=[
            "Winter fog visibility reduction (<150m)",
            "Approach queue at Ghaziabad junction bottleneck"
        ],
        section_congestion_level=0.92,
        weather_fog_active=True,
    )

    print(f"  -> Generated By: {res_fog['generated_by']}")
    print(f"  -> Summary     : {res_fog['summary']}")
    print(f"  -> Bullet Points:")
    for bp in res_fog["operational_bullet_points"]:
        print(f"     * {bp}")

    # 3. FastAPI Endpoint Integration Test
    print("\n[3] Testing POST /api/v1/trains/12302/ai-explain via FastAPI TestClient...")
    client = TestClient(app)
    resp = client.post("/api/v1/trains/12302/ai-explain", json={"station_code": "PRYJ"})
    assert resp.status_code == 200, f"Expected 200, got {resp.status_code}: {resp.text}"
    api_data = resp.json()

    print(f"  -> API Response Train : {api_data['train_name']} ({api_data['train_number']})")
    print(f"  -> Target Station     : {api_data['target_station']}")
    print(f"  -> AI Summary         : {api_data['summary']}")
    print(f"  -> Passenger Advice   : {api_data['passenger_advice']}")
    print(f"  -> Engine Provenance  : {api_data['generated_by']}")

    print("\n" + "=" * 82)
    print("[+] AI Explanation Layer (LLM + Zero-Fail Fallback) VERIFIED!")
    print("=" * 82)


if __name__ == "__main__":
    test_ai_explainer()
